### ISSUE TITLE
Position and sorting of content is reset after going back to search results

### ISSUE THREAD

**Issue by MrRedstoneToGo** [modrinth/code#1080]
### Describe the bug

After watching a mod/ressourcepack/... and then going back, the order and position of all Minecraft is reset but the page number on which you were before is still the same

### Steps to reproduce

1. Browse a mod pack
2. Set the button next to "Sort by:" to any except "Relevance"
3. Scroll down to the last entry
4. Click on it
5. Go back to search results. After "Sort by:" is "Relevance" and you're at the top of the page

### Expected behavior

When you come back everything is as you left it

### System information

Windows 11, Modrinth 0.6.3

**Comment by KnifesmithCode** [comment]
Likely caused by the scrollBehavior chosen here: https://github.com/modrinth/theseus/blob/3ff0ff238a4360960a8fee26d45094f92c8fefc5/theseus_gui/src/routes.js#L140C1-L143C5

Not sure why `top: 0` was chosen, but this appears to be intended behavior - although I agree that it should be changed in this case. Could change the global behavior (probably the wrong thing to do), or could filter based on routes relevant to the mod pack screen (probably the right thing to do, since this was an intentional change in #127). Maybe @Geometrically could give some insight.

**Comment by palexdev** [comment]
Hello, can we please have a better navigation system like on the CurseForge app?

The Modrinth app not only scrolls to top but also returns to the first page when opening a page and going back

**Comment by RoarkCats** [comment]
I also have the issue that the App returns to the first page of search, not whatever page you were on (more annoying than just losing scroll)

Note: I usually use my mouse button to go back not the icon if it makes a difference

**Comment by GitPlayer3** [comment]
this is SUUUUCH an annoying bug. please fix

**Comment by IMB11** [comment]
Fixed in #6896

**Comment by RamuneNeptune** [comment]
On Modrinth App 0.18.2 this still doesn't appear fixed

1. Go to the Discover page, any tab
2. Scroll down
3. Click into a mod/modpack/resource pack etc.
4. Press the back arrow
5. You will be reset all the way to the top of the page

**Comment by IMB11** [comment]
Can't reproduce @RamuneNeptune 

https://github.com/user-attachments/assets/8735666b-374e-4016-80ba-c4e611f2d2f1

**Comment by RamuneNeptune** [comment]
@IMB11 Ah maybe I was confused by the wording of this issue

I was chasing this one https://github.com/modrinth/code/issues/404 which absolutely does my head in while installing a heap of content (doesn't return to where you'd scrolled after pressing back after clicking into content): https://github.com/user-attachments/assets/e255974f-2e2d-4744-806b-ae60d591c42b

Great that one of the other things that drove me crazy is fixed though (no longer returns you to page 1 after clicking into content then going back)
