### ISSUE TITLE
Changelog deduplication ignores filters

### ISSUE THREAD

**Issue by TropheusJ** [modrinth/code#1571]
### Describe the bug

Changelogs will be combined when multiple versions share the same one:
![image](https://github.com/modrinth/knossos/assets/60247969/c5719150-0ace-4e3f-927a-30665be33898)

However, when filtering the displayed versions, this still applies, even if the only remaining visible version is hidden by the filters:
![image](https://github.com/modrinth/knossos/assets/60247969/28205369-ea86-45fe-b9c7-f8c96f2f572b)

### Steps to reproduce

- Go to https://modrinth.com/mod/create-fabric/changelog
- See that `1.18.2 v0.5.1.b Patch 2` is hidden by `1.19.2 v0.5.1.b Patch 2` (correct)
- filter by 1.18.2
- see `1.18.2 v0.5.1.b Patch 2` is still hidden by `1.19.2 v0.5.1.b Patch 2`, despite it not being visible. (incorrect)
The dotted lines claim Patch 2 and Patch 1 share identical changelogs, which they do not.

### Expected behavior

Only combine changelogs of visible versions

**Comment by Minenash** [comment]
Fixed at some point

**Comment by Poopooracoocoo** [comment]
> Fixed at some point

Just not deployed to the site yet? 

I face this issue often. The steps in this issue still reproduce the issue. I just tried to look at https://modrinth.com/mod/distanthorizons/changelog?l=fabric&g=1.20.1 and it was useless. Each release has changelogs.

I even still have the "hydration issues" on Chromium. I have to refresh the site immediately after opening it for it to work properly. And sometimes that doesn't even work. Longstanding issues like these make it harder to advocate for Modrinth
