### ISSUE TITLE
Invisible ads playing sound on Home screen

### ISSUE THREAD

**Issue by MrEndermen** [modrinth/code#2443]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

v0.8.7

### What operating systems are you seeing the problem on?

Windows

### Describe the bug

When the home screen is selected, ads are playing sound.

### Steps to reproduce

Leave Modrinth on the "Home" screen, and wait. It will play a PlayStation ad that you can not see.

### Expected behavior

audio playing for a Playstation game.

### Additional context

Annoying AF

**Comment by noah-pm-dev** [comment]
I have experienced this same issue three times. Right after hearing it, "Microsoft Edge WebView2" appears as a new sound source, and goes away when the app is closed. I'm assuming that webview is used to display the ads, but is being improperly packaged. I can also confirm that the playstation ad has been 2 of the three ads that I heard, I do not know what the third one was. Also, the "mute" button on the ad is not visible but still useable on these broken ads.

**Comment by darkwiz666** [comment]
It's some stupid Playstation game Advert. Ditto on the ad not being displayed, too.

**Comment by Naruyoko** [comment]
> Additionally, this happens on the home screen and in the main screen for profiles (only two places I've tested it)

I also gotten this on the log viewer, which retains the sidebar (including the ad) from the profile home screen.

**Comment by Naruyoko** [comment]
I have been getting invisible, audio ads again after updating to 0.9.0.

**Comment by Geometrically** [comment]
Sorry about this! We have released v0.9.1 which should permanently fix the issue!

**Comment by Apollounknowndev** [comment]
This did not appear to fix the issue, I just had it occur to me on 0.9.1.

**Comment by darkwiz666** [comment]
> This did not appear to fix the issue, I just had it occur to me on 0.9.1.

Impossible, since the issue was it showing up on text-button that WERE on the left of the screen, above the ads.


Those text-butttons are now are buttons in a shelf, and the ads are now show on the far-right of the screen...
![Image](https://github.com/user-attachments/assets/35b06918-7a5d-4cdf-bf4a-4976dbb35a19)

**Comment by darkwiz666** [comment]
Might want to actually report what the ad is, since it'll replay at least 5 times in the next hour anyway...
