### ISSUE TITLE
Withdrawing rewards program revenue doesn't work

### ISSUE THREAD

**Issue by LilBroCodes** [modrinth/code#3455]
### Please confirm the following.

- [x] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [x] I have tried resolving the issue using the [support portal](https://support.modrinth.com)

### What browsers are you seeing the problem on?

Firefox

### Describe the bug

Trying to withdraw my $0.50 from the rewards program through PayPal in the Hungary region, but instead I am getting an error from PayPal, "INSUFFICIENT FUNDS". I also tried with just $0.40 and that didn't work either. Here's a screenshot: 

![Image](https://github.com/user-attachments/assets/076a4878-2a5c-45a5-a56e-9a6667176d22)

### Steps to reproduce

1. Go to the [withdraw](https://modrinth.com/dashboard/revenue/withdraw) page
2. Try to withdraw with method PayPal, in region Hungary (Possibly only on my account, not sure)

### Expected behavior

The $0.50 is transferred over with PayPal. (- processing fees)

**Comment by LilBroCodes** [comment]
Added comment: I also tried a $0.25 transfer, that didn't work either.

**Comment by MTRangeVR** [comment]
same here I'm having the same issue

**Comment by sakura-ryoko** [comment]
I can reproduce this issue also; but with a different balance number.

**Comment by sakura-ryoko** [comment]
I then tried using "Venmo" and am receiving a different error `VALIDATION_ERROR`

**Comment by izmystic** [comment]
https://discord.com/channels/734077874708938864/734084055225597973/1356948907468525668
## 💰 PayPal and Venmo temporarily unavailable
PayPal and Venmo payouts are currently temporarily unavailable due to our PayPal account running low on funds. It may take a few days for the transfer from our bank to PayPal to clear. We will update here when these withdraw methods are available again.

**Comment by regfunkid** [comment]
> https://discord.com/channels/734077874708938864/734084055225597973/1356948907468525668
> 
> ## 💰 PayPal and Venmo temporarily unavailable
> PayPal and Venmo payouts are currently temporarily unavailable due to our PayPal account running low on funds. It may take a few days for the transfer from our bank to PayPal to clear. We will update here when these withdraw methods are available again.

Transfers are still unavailable--they'll probably be back online next week? Maybe the week after next, if i'm being hopeful

**Comment by quat1024** [comment]
It appears their bank transfer went thru, i just transferred some

**Comment by sakura-ryoko** [comment]
Same

**Comment by triphora** [comment]
This has since been fixed. Blame PayPal for taking so long to deal with transfers

**Comment by fzzyhmstrs** [comment]
appears to be happening again (April 16).

![Image](https://github.com/user-attachments/assets/2e1c0190-f389-422d-9413-746aacb930de)

**Comment by GamerMedic** [comment]
I'm having the same issue on 18/04/2025

![Image](https://github.com/user-attachments/assets/c0113ce9-121c-4f80-a5a8-50e7fcb67573)

**Comment by triphora** [comment]
PayPal is taking forever once again

**Comment by AzisterZodep** [comment]
same issue on 20/04/2025

**Comment by triphora** [comment]
Fixed now

**Comment by sakura-ryoko** [comment]
This is happening again today.

**Comment by sakura-ryoko** [comment]
![Image](https://github.com/user-attachments/assets/44f56a16-68b2-4372-9646-220fdc6fcbec)

There was a post on the Discord saying that this was fixed and I still cannot withdrawal using PayPal; and this Issue was already marked resolved.

It clearly has not been resolved @triphora

**Comment by regfunkid** [comment]
Guys, we just gotta be patient. Every time the issue appears is because Paypal just takes forever with transfers, nothing Modrinth can do on their end. I think they should just close the issue but keep it visible (or maybe add a section about it to the FAQ) so folks know what's going on.
