### ISSUE TITLE
Prompted to Verify/Set Environment on Datapacks, when trying to set, returns Error.

### ISSUE THREAD

**Issue by rotgruengelb** [modrinth/code#4281]
### Please confirm the following.

- [x] I checked the [existing issues](https://github.com/modrinth/code/issues?q=is%3Aissue) for duplicate problems
- [x] I have tried resolving the issue using the [support portal](https://support.modrinth.com)

### What browsers are you seeing the problem on?

Firefox

### Describe the bug

<img width="948" height="128" alt="Image" src="https://github.com/user-attachments/assets/04ce5e14-ed45-447d-8ada-c592caf73470" />

<img width="1553" height="1089" alt="Image" src="https://github.com/user-attachments/assets/5fd79759-3f6b-4ac8-8b3d-87fc0d76ec6c" />

### Steps to reproduce

1. Go to Dashboard
2. See the Warning to review Environment on Datapack (that is also Auto Bundled as a Mod)
3. When trying to set the correct Env get PATCH 400 Status Code

### Additional context

Prompted to Verify/Set Environment on Datapacks, when trying to set, returns Error.

**Comment by 4drian3d** [comment]
I am experiencing the same issue when updating the configuration of my two mods, but it has allowed me to update the information for my modpack

**Comment by mopsy14** [comment]
I am experiencing the same issue with 1 of my 5 mods.

**Comment by mopsy14** [comment]
Might be noteworthy that I had the issue while it was set to "server-side only -> works in single player too" just like in the original post.

**Comment by Schinkennugget** [comment]
Have the same issue

**Comment by Prospector** [comment]
This has been fixed. @rotgruengelb I used your Hoppers from Barrels project to test with and set your environment for you. Please double-check that it's correct now.

**Comment by rotgruengelb** [comment]
> This has been fixed. [@rotgruengelb](https://github.com/rotgruengelb) I used your Hoppers from Barrels project to test with and set your environment for you. Please double-check that it's correct now.

yes, seams to be all correct. thx

**Comment by tjb3171** [comment]
i'm still having this issue. trying to set the environment of my datapack (also having been packaged as a mod) to "serverside - works in singleplayer too"

**Comment by Prospector** [comment]
Unfortunately, we had to pull the backend deploy that fixed this due to an unrelated bug that went out with it. Will be live again soon
