### ISSUE TITLE
Missing Neoforge loader versions

### ISSUE THREAD

**Issue by maxter420** [modrinth/code#4530]
### Please confirm the following.

- [x] I checked the [existing issues](https://github.com/modrinth/code/issues?q=is%3Aissue) for duplicate problems
- [x] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [x] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

0.10.10

### What operating systems are you seeing the problem on?

Windows

### Describe the bug

as it says on the title, modrinth is only displaying 1.20.1 and 1.21.10 versions of neoforge and even when i had it in 1.21.1 before i changed it thinking i repaired it, it would register saying that it wasn't a supported version of neoforge.

<img width="793" height="501" alt="Image" src="https://github.com/user-attachments/assets/9ddbe3c0-4c24-4a8b-a8a1-7ac1006da78e" />

### Steps to reproduce

1.Go to a modpack Settings
2.Go to the installation tab
3.Click on Neoforge and look for game versions

### Expected behavior

to the multiple versions of neoforge to select from

**Comment by HappyGFX** [comment]
I have same error

**Comment by chichaginigor-coder** [comment]
SAME

**Comment by Caliamara** [comment]
Same, broke all my packs

<img width="2048" height="1536" alt="Image" src="https://github.com/user-attachments/assets/6597faae-08c6-4fef-976c-a06653002faf" />

**Comment by MelloDew** [comment]
I have same error with v0.10.8 on Ubuntu Linux

**Comment by KSAW00** [comment]
Same Issue! 

<img width="214" height="64" alt="Image" src="https://github.com/user-attachments/assets/292b2654-08c5-480f-8f61-3106aa5ca15f" />

<img width="615" height="440" alt="Image" src="https://github.com/user-attachments/assets/c54d4d8f-36f7-4a6f-9eae-cedeac4131f3" />

**Comment by KirayXak8** [comment]
КТО ПОНЯЛ КАК РЕШИТЬ ЭТУ ПРОБЛЕМУ ?

**Comment by vitheking** [comment]
having the same issue. 1.21.1 does not exist. prompted to use 1.21.10 instead.

<img width="884" height="645" alt="Image" src="https://github.com/user-attachments/assets/2c41854c-6359-43a4-b634-ef7aee7f4a4d" />
<img width="866" height="626" alt="Image" src="https://github.com/user-attachments/assets/bf6ea86e-582f-40d4-86ae-53aff3ba237a" />

**Comment by MrGreenscreenWFW** [comment]
Same Error

**Comment by Bink-lab** [comment]
Me aswell

**Comment by TheCommandCraft** [comment]
I have the same issue, my friend has that too. I think the whole app for everyone is broken. Please review. I cannot join my MC server, all my active players too, because it the modpack is on modrinth.

**Comment by Yaghito3** [comment]
Hi, if you did see the discord it should be fixel in a couple minutes (5-20)

**Comment by maxter420** [comment]
i am not in the discord but i am going to check if the issue is fixed and when it is i will close this asap

**Comment by vitheking** [comment]
it isn't

**Comment by Caliamara** [comment]
> i am not in the discord but i am going to check if the issue is fixed and when it is i will close this asap

They're actively working on it. I think it's a big issue lolol

**Comment by Yaghito3** [comment]
Fixed

**Comment by Frenk012** [comment]
Still not on linux apparently, the last update of the image is at 00:27 of today and it still show only those options

**Comment by DootLoot** [comment]
Still a bug as of today

**Comment by davidnikolic** [comment]
<img width="964" height="662" alt="Image" src="https://github.com/user-attachments/assets/b52a47c7-372b-403f-9511-23130d6b81ac" />

Same problem here...

**Comment by Prospector** [comment]
NeoForge broke their version metadata again. We're looking into a more long-term solution on our end to mirror their data so this isn't possible to happen again.

**Comment by Radagast101** [comment]
What the hell? I was playing NeoForge 1.21.1 YESTERDAY and .... oh. Thanks, Prospector. Damn.

**Comment by manu-palmero** [comment]
Can the instance be run manually with a manually downloaded NeoForge while the problem is being fixed?

**Comment by SuperDerrington** [comment]
It's working again :)

**Comment by manu-palmero** [comment]
Yeah, it works :D
