### ISSUE TITLE
Auto-downloaded dependencies don't respect mod loader in app

### ISSUE THREAD

**Issue by gilendan** [modrinth/code#4544]
### Please confirm the following.

- [x] I checked the [existing issues](https://github.com/modrinth/code/issues?q=is%3Aissue) for duplicate problems
- [x] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [x] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

0.10.10 Windows 10.0.26200

### What operating systems are you seeing the problem on?

Windows

### Describe the bug

I've been trying to create a personal, custom modpack/instance with Fabric loader for Minecraft version 1.20.1.  When I go through the app to add mods, the mods that have dependencies, the dependencies get installed but for some reason the Forge versions get installed instead of the correspondent Fabric versions.  I have to go through every mod to ensure the correct loader version is installed.  This started happening 2 days ago for me and I've tried to do several different instances and it's happening every time.  For example, I installed a mod that required Cloth Config API and instead of installing the Fabric version it installed the Forge version.  I had to manually change it.

**Comment by Prospector** [comment]
Could you provide the exact mod and version you tried installing so we can reproduce?

**Comment by gilendan** [comment]
Sure!  One example is the mog Create Goggle Placement by LieOnLion as it requires MidnightLib mod.  I installed the Create Goggle Placement mod and it automatically installed the Forge version of MidnightLib.  Hope this helps.  I'm providing this one as it happened earlier today.

**Comment by Prospector** [comment]
Can confirm, thanks!

**Comment by UpcraftLP** [comment]
Same here, installing creeper overhaul in a 1.21.1 neoforge profile pulls in resourceful config / resourceful lib for fabric

<img width="2070" height="393" alt="Image" src="https://github.com/user-attachments/assets/a1ea0a5d-1a2a-4f51-bc8c-adb6bc16b72d" />

**Comment by nourkagha** [comment]
Yep same issue (on Fabric 1.21.10).

NeoForge dependencies are being installed instead of Fabric.

For example, installing FancyMenu mod on Fabric installs the dependencies Konkrete and Melody as the NeoForge instead of Fabric versions.

This makes the instance not start unless they're replaced with the correct Fabric dependencies.

**Comment by box777555888** [comment]
Issue still exists as of Modrinth App 0.10.15
Build windows 10.0.22621
When trying to install the mod "Combat Roll" for fabric it downloads a forge version of Cloth Config API.

<img width="768" height="187" alt="Image" src="https://github.com/user-attachments/assets/d24231f8-2080-4954-a146-59a9c93e7e97" />

**Comment by Hallskii** [comment]
Hi there, this has been fixed and shipped to the app

**Comment by gilendan** [comment]
The issue still persists.  I have a Fabric modpack, I'm creating and when I installed Via Romana mod, it installed the Forge version of the Data Anchor mod dependency.  See screenshot.

<img width="2424" height="1006" alt="Image" src="https://github.com/user-attachments/assets/b43d71fb-acac-4bb2-a1a4-ee365313fbb0" />

**Comment by UpcraftLP** [comment]
Just updated to `Modrinth App 0.10.18`, and purged my app cache as well. Then tried installing creeper overhaul again. The issue still persists.

<img width="2085" height="446" alt="Image" src="https://github.com/user-attachments/assets/a535c08c-aced-4347-8a67-9bab8095e3ce" />

**Comment by Prospector** [comment]
it seems 0.10.18 was missing the commit that fixed this, somehow

**Comment by Prospector** [comment]
The fix is now available in 0.10.19

**Comment by UpcraftLP** [comment]
> The fix is now available in 0.10.19

Yup, works now

<img width="1394" height="394" alt="Image" src="https://github.com/user-attachments/assets/e07a43fa-712d-4af9-a599-c96150e89aeb" />
