### ISSUE TITLE
Modrinth app keeps crashing after I AltTab

### ISSUE THREAD

**Issue by Pratschi** [modrinth/code#4796]
### Please confirm the following.

- [x] I checked the [existing issues](https://github.com/modrinth/code/issues?q=is%3Aissue) for duplicate problems
- [x] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [x] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

0.10.19

### What operating systems are you seeing the problem on?

Windows

### Describe the bug

I just leave the Modrinth App with AltTab to Opera GX and it no longer works with AltTAbbing, minimizing the browser does show the app, but it doesn't answer and then Windows identifies it has crashed after clicking on it a few times.

Opening it again works fine, until you alttab again

It only happens sometimes

### Steps to reproduce

1. Open Modrinth App
2. Alt + Tab
3. Try to open it Again
4. Will only close after Windows realizes it has crashed (Alt F4 doesn't work)

### Expected behavior

Modrinth app to open

### Additional context

Windows 11 Pro 25H2 26200.7171
Experience Pack  1000.26100.265.0

**Comment by Hallskii** [comment]
Hi I can't reproduce this, alt tabbing works fine

**Comment by ghost** [comment]
> Hi I can't reproduce this, alt tabbing works fine

Iv had this issue too could be related to #3952

**Comment by Yaapo** [comment]
I also have this issue. I've tried modifying the target path in the Modrinth App's properties and disabling HAGS. No effect.

**Comment by Hallskii** [comment]
@YoureIronic @Pratschi We pushed something for this. Either of you having this on the latest build?

**Comment by Pratschi** [comment]
It seems to be fixed, but when spamming alt+tab it crashes (Windows says it's not responding)

**Comment by Yaapo** [comment]
Still not fixed.

Sent with [Proton Mail](https://proton.me/mail/home) secure email.

**Comment by ghost** [comment]
> [@YoureIronic](https://github.com/YoureIronic) [@Pratschi](https://github.com/Pratschi) We pushed something for this. Either of you having this on the latest build?

I recently switched to Linux Mint and never had this issue ever since.

**Comment by Hallskii** [comment]
Can one of you share a video?

**Comment by Pratschi** [comment]
I managed for it to crash again, please see the Video (Drive Upload, because GitHub failed), like in 0:50, it crashes, becomes unresponsive (Clicking or typing doesn't work, also takes spamming X or Alt F4 for it to finally close, or until it says it crashed)

**Comment by nanto2016** [comment]
Still happens to me, anything I can do to fix this?

**Comment by TrapNouz** [comment]
still happening for me this is so annoying i can't even end tasj from taskbar
